---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/login":
    post:
      summary: create session
      responses:
        '200':
          description: successful
  "/api/v1/transactions/credit":
    post:
      summary: credit transaction
      responses:
        '200':
          description: successful
  "/api/v1/transactions/debit":
    post:
      summary: debit transaction
      responses:
        '200':
          description: successful
  "/api/v1/transactions/transfer":
    post:
      summary: transfer transaction
      responses:
        '200':
          description: successful
  "/api/v1/wallets/get_balance":
    post:
      summary: get_balance wallet
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
