default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  host: localhost

development:
  <<: *default
  database: rortest_wallet

test:
  <<: *default
  database: rortest_wallet_test

production:
  <<: *default
  database: rortest_wallet_prod